# Site settings
title: josephbales.com
email: joey@josephbales.com
baseurl: ""
url: "https://josephbales.com"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title:output_ext

# Feed
plugins:
  - jekyll-feed
  - jekyll-sitemap
